#! /bin/bash

day=$(( ($(date +%s) / (3600 * 24)) % 2))
hostname=$(hostname -s)

if [ "x$1" != "x" ]; then
  hostname=$1
fi
if [ "x$2" != "x" ]; then
  day=$2
fi

while read i; do
  ./local-launcher $i
done < cron/$hostname-$day
