#! /bin/sh
ssh -C 192.168.10.11 "psql --tuples-only -d osm -c \"SELECT word FROM dicosm_words WHERE valide = true OR correction = '';\" osm" | sed -r "s/(^ +| +$)//g" > DicoJessie
ssh -C 192.168.10.11 "psql --tuples-only -d osm -c \"SELECT word||':'||correction FROM dicosm_words WHERE valide = false AND correction <> '';\" osm" | sed -r "s/(^ +| +$)//g" > CorrJessie
