from typing import List, Dict, Union

class Visitor():

    def set_since_timestamp(self, timestamp: int) -> None: ...

    def node(self, osmid: int, lon: int, lat: int, tags: Dict[str, str]) -> None: ...

    def filtered_nodes(self) -> List[int]: ...

    def way(self, osmid: int, tags: Dict, refs: List[int]) -> None: ...

    def filtered_ways(self) -> List[int]: ...

    def relation(self, osmid: int, tags: Dict, ref: List[Dict[str, Union[str, int]]]) -> None: ...

    def filtered_relations(self) -> List[int]: ...

def read_osm_pbf(pbf: str, visitor: Visitor) -> None: ...
