from typing import List, Dict, Union

class Visitor():
    def node(self, osmid: int, lon, lat, tags: Dict[str, str]) -> None: ...

    def way(self, osmid: int, tags: Dict, refs: List[int]) -> None: ...

    def relation(self, osmid: int, tags: Dict, ref: List[Dict[str, Union[str, int]]]) -> None: ...


def read_osm_pbf(pbf: str, visitor: Visitor) -> None: ...
